### ISSUE TITLE
possible duplicate of another project

### ISSUE THREAD

**Issue by Minetest-j45** [TechDudie/mc#3]
have you checked out https://git.minetest.land/MineClone2/MineClone2/src/branch/mineclone5 ? i think it has the same goals (1.16)

**Comment by TechDudie** [comment]
MineClone5 is just a few mods currently, I am starting off quickly because i have a massive amount of time on my hands currently, and i support a free open-source Minecraft clone. Anyone is welcome to use and edit my code under the terms of the license (i forgot which one it is see LICENSE.txt)

**Comment by pl608** [comment]
i think it is MIT that is what you description of yours self says

**Comment by TechDudie** [comment]
it’s GPLv3, because the mods in the modpack are GPLv3 too

**Comment by pl608** [comment]
ok
