### ISSUE TITLE
Something Wrong With Bamboo...

### ISSUE THREAD

**Issue by pl608** [TechDudie/mc#4]
I downloaded the mod and extracted it into the mod folder then ran the new mod and...
# It Crashed!
(well in the way that it failed to load the game(though then again that might be a crash...(i dont know(😣))))
there was an error in the code and since I don't know to well what is wrong besides for it thinks it needs a = near something.

**Comment by pl608** [comment]
![image](https://user-images.githubusercontent.com/78400949/113498195-a69e7900-94bf-11eb-9770-03c61f8da075.png)

**Comment by TechDudie** [comment]
Ah, looks like my attempt at a single-line funtion failed...
