### ISSUE TITLE
Add Conduits

### ISSUE THREAD

**Issue by TechDudie** [TechDudie/mc#5]

**Comment by TechDudie** [comment]
Conduits are added and are activatable, but they are uncraftable and have no use.

**Comment by TechDudie** [comment]
Ok, conduits give the water breathing effect, the night vision effect, and the speed effect (level 4, is this too much?) whenever you’re in range of 96 nodes and the conduit is touching water on its sides. However, they are still uncraftable.

**Comment by TechDudie** [comment]
Er wait a moment, seems like I made a indentation error.

**Comment by TechDudie** [comment]
Now I have added items to craft the conduit in mc_ocean, however, the items themselves are uncraftable. This is intended, though, as this is the same in Minecraft. I will add the recipe soon.

**Comment by TechDudie** [comment]
All done. 😄

**Comment by TechDudie** [comment]
Er wait a sec...

**Comment by TechDudie** [comment]
I forgot. Textures are still needed. In this case, the conduit textures, the nautilus shell textures, and the heart of the sea textures are needed. I will get around to making them soon.

**Comment by pl608** [comment]
i can help

**Comment by TechDudie** [comment]
Thx

**Comment by pl608** [comment]
![heart](https://user-images.githubusercontent.com/78400949/113632951-e6c93d00-9620-11eb-8f4c-cfa3f77bb805.png)

**Comment by pl608** [comment]
now just right-click save image!

**Comment by TechDudie** [comment]
Ok, heart image uploaded

**Comment by TechDudie** [comment]
Ill add compat with the schematics and mcl_fishing ltr

**Comment by pl608** [comment]
![shell](https://user-images.githubusercontent.com/78400949/113633265-7a9b0900-9621-11eb-9c6c-7497fc253ca1.png)

**Comment by pl608** [comment]
heres another

**Comment by TechDudie** [comment]
Ok uploading image

**Comment by TechDudie** [comment]
ok, i have a not so bad conduit image.

**Comment by TechDudie** [comment]
look at release 0.0.6.1 for finished conduits
