### ISSUE TITLE
Bamboosold again...(only this time it is condiuts)

### ISSUE THREAD

**Issue by pl608** [TechDudie/mc#6]
getting a crash again. Something about a prefix
![Screenshot 2021-04-05 212922](https://user-images.githubusercontent.com/78400949/113659000-0169d900-9656-11eb-979d-e73065be679b.png)
sooo yeah... can you fix?

**Comment by TechDudie** [comment]
Lol typo in mod name

**Comment by TechDudie** [comment]
Will fix soon

**Comment by pl608** [comment]
i think we should test before a realsease techy

**Comment by TechDudie** [comment]
I only test before a release a minor version

**Comment by TechDudie** [comment]
These are release patches I don’t test em yet

**Comment by pl608** [comment]
ok
